# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - club_db:/var/lib/mysql/club_db

  api:
    build:
      context: .
      dockerfile: api.dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${DB_NAME}
    ports:
      - '8080:8080'
    depends_on:
      - db

volumes:
  club_db: