# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: club_api_spring
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - club_db:/var/lib/mysql/club_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

volumes:
  club_db: